app/models.py
from app import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from app import login_manager

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin,db.Model):
    __tablename__ = 'users'
    
    id = db.Column(db.Integer, primary_key = True)
    username = db.Column(db.String(255))
    email = db.Column(db.String(255))
    password_secure = db.Column(db.String(255))
    OMPs = db.relationship('OMP', backref = 'user', lazy = 'dynamic')
    comments = db.relationship('Comment', backref = 'user', lazy = 'dynamic')
    
    @property
    def password(self):
        raise AttributeError('You cannot read password')
    
    @password.setter
    def password(self, password):
        self.password_secure = generate_password_hash(password)
        
    def verify_password(self, password):
        return check_password_hash(self.password_secure, password)
    
    def __repr__(self):
        return f'User {self.username}'
    
class OMP(db.Model):
    __tablename__ = 'omp'
    
    id = db.Column(db.Integer, primary_key = True)
    title = db.Column(db.String(255))
    content = db.Column(db.String)
    votes = db.Column(db.Integer)
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'))
    comments = db.relationship('Comment', backref = 'omp', lazy = 'dynamic')
    
    def __init__(self, title, content):
      self.title = title
      self.content = content
      
    def save_omp(self):
        db.session.add(self)
        db.session.commit()
        
    @classmethod
    def get_omp(cls):
        omps = OMP.query.filter_by().all()
        return omps
        
class Comment(db.Model):
    __tablename__ = 'comments'
    
    id = db.Column(db.Integer, primary_key = True)
    message = db.Column(db.String)
    OMP_id = db.Column(db.Integer,db.ForeignKey('omp.id'))
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'))
    
    def __init__(self, message):
      self.message = message
      
    def save_comment(self):
        db.session.add(self)
        db.session.commit()
        
    @classmethod
    def get_comments(cls):
        comments = Comment.query.filter_by().all()
        return comments
        

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SelectField,SubmitField
from wtforms.validators import Required
from app import db


class OMPForm(FlaskForm):
    title = StringField('Title', validators = [Required()])
    description = TextAreaField('OMP Description')
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_mail import Mail

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
db = SQLAlchemy()
mail = Mail()

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config_options[config_name])
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint, url_prefix = '/success')
    
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint)
    
    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__)
from . import views, error

app/main/views.py
from flask import render_template,redirect,url_for,request,abort
from . import main
from ..models import User,OMP,Comment
from .forms import OMPForm
from app import db

@main.route('/')
def index():
    title = 'MAKE AN EXQUISITE IMPRESSION'
    omps = OMP.query.all()
    
    return render_template('home.html', title = title, omps = omps)

@main.route('/profile/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)
    title = 'Profile'
    
    return render_template('profile/profile.html', title = title)

@main.route('/new/omp', methods = ['GET', 'POST'])
def new_omp():
    form = OMPForm()
    if form.validate_on_submit():
        title = form.title.data
        omp = form.description.data
        new_omp = OMP(title = title, content = omp)
        db.session.add(new_omp)
        db.session.commit()
        
        return redirect(url_for('.index'))
    
    title = 'New OMP'
    return render_template('new_omp.html', title = title, omp_form = form)

@main.route('/opm/<int:id>')
def opm(line_id):
    Pickup = OMP.query.filter_by(opm.id == line_id).first()
    if Pickup is None:
        abort(404)
    
    return render_template('full_opm.html', pickup = Pickup)

app/templates/base.html
{% extends "bootstrap/base.html" %}


{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

app/templates/full_opm.html
{% extends "base.html" %}
{% block content %}
    <h1>Happy</h1>
{% endblock %}

app/templates/home.html
{% extends "base.html" %}
{% import 'macro.html' as macro %}

{% block content %}
    <div class="home">
        {{macro. displayPickupLines(omps)}}
    </div>
    <div class="text-center">
        <a href="{{url_for("main.new_omp")}}"><button class="btn btn-danger">NEW OMP</button></a>
    </div>
{% endblock %}

app/templates/macro.html
{% macro displayPickupLines(opm_list) %}
    {% for opm in opm_list %}
        <div class="container">
            <div class="row">
                <div class="col-md-2"></div>
                <div class="col-md-8">
                    {{ opm.title }}
                    <br>
                    <a href="{{url_for("main.opm")}}"><button class="btn btn-danger">Read More</button></a>
                </div>
                <div class="col-md-2"></div>
            </div>
        </div>
    {% endfor %}
{% endmacro %}

app/templates/navbar.html
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
                {% if current_user.is_authenticated %}
                    <a href="{{url_for("main.index")}}" class="navbar-brand">OMP</a>
                {% else %}
                    <a href="/" class="navbar-brand">One Minute Pickup-lines</a>
                {% endif %}

        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                    <li><a href="{{url_for('main.profile', uname=current_user.username)}}">Profile</a></li>
                    <li><a href="{{url_for('auth.logout')}}">Sign Out</a></li>
                {% else %}
                    <li><a href="{{url_for('auth.login')}}">Sign In</a></li>    
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

app/templates/new_omp.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                {{wtf.quick_form(omp_form)}}
            </div>
            <div class="col-md-2"></div>
        </div>
    </div>
{% endblock %}

app/templates/profile/profile.html
{% extends "base.html" %}

<h1>Hi {{user.username}} this is you profile</h1>